language: node_js
node_js:
  - 8
  - 10
  - 11
cache:
  directories:
    - "node_modules"

script:
  - npm run tsc
  - npm run test:coverage
after_success:
  - npm run build

branches:
  only:
    - master

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      script: skip # Skip the tests this time
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
