language: node_js
node_js:
  # TODO Add Node 10 again once jsdom/jsdom#2961 is fixed
  # - 10
  - 12
  - 13
  - 14
script:
  - npm run tsc
  - npm run test:coverage && npx codecov
after_success:
  - npm run build
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      if: branch = master
      node_js: lts/*
      script: skip # Skip the tests this time
      deploy:
        provider: script
        skip_cleanup: true
        script: "npx semantic-release"
