language: node_js
node_js:
  - 8
  - 10
  - 11
cache:
  directories:
    - "node_modules"

script:
  - npm run tsc
  - npm run test
after_success:
  - npm run test:coverage
  - npm run build

branches:
  only:
    - master
