name: build

on: [push, pull_request]

env:
  HUSKY: 0

jobs:
  test:
    name: Build, lint, and test on Node.js ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm@v7
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run tsc --workspaces

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test --workspace=main -- --ci --coverage --maxWorkers=2

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: main/

      - name: Build
        run: npm run build --workspace=main

      - name: Build the docs
        run: npm run docs

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.repository_owner == 'bjoluc' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --workspace=main

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release --workspace=main
